name: 'icure_medical_device_dart_sdk'
description: 'icure high level sdk for medical devices'
version: '1.0.0'

#homepage: 'homepage'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: '>=0.13.0 <0.14.0'
  intl: '^0.17.0'
  meta: '^1.7.0'
  uuid: ^3.0.5
  icure_dart_sdk:
    git:
      url: https://github.com/icure-io/icure-dart-sdk.git
      ref: 73c80bde7bb4a1627db5eba44ebae873dc11c59b
  pointycastle: ^3.5.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
